### ISSUE TITLE
workflow failed: " invalid spec: cannot convert int64 to string"

### ISSUE THREAD

**Issue by Yancey1989** [couler-proj/couler#108] opened 2020-11-02 07:59 UTC
The submitted workflow failed with the following log:

``` text
...
Status:
  Conditions:
    Status:     True
    Type:       Completed
  Finished At:  2020-11-02T07:50:18Z
  Message:      invalid spec: cannot convert int64 to string
  Phase:        Failed
  Started At:   2020-11-02T07:50:18Z
Events:         <none>
```

The workflow YAML needs double quotation marks  on the integer environment variable value, such as the following code snippets, `value: 12300` should be `value: "12300"`

``` YAML
...
    - name: sqlflow-138
      container:
        image: sqlflow/sqlflow
        command:
          - "if [[ -f /opt/sqlflow/init_step_container.sh ]]; then bash /opt/sqlflow/init_step_container.sh;\
            \ fi && set -o pipefail && mkdir -p /home/admin/logs && (step -e \"SELECT\
            \ * FROM iris.test\nTO EXPLAIN sqlflow_models.my_dnn_model\nWITH label_col=class\n\
            INTO iris.explain_result_table;\n\" 2>&1 | tee /home/admin/logs/step.log)\
            \ && sleep 0"
        env:
...
          - name: SQLFLOW_PARSER_SERVER_PORT
            value: 12300
          - name: SQLFLOW_TEST
            value: workflow
...

**Comment by terrytangyuan** [comment] 2020-11-09 21:52
Providing an update here after discussed with @Yancey1989 offline on November 2nd:
* As a workaround, adding escaped quotes around the variable value would resolve the issue: `run_container(env={"SQLFLOW_PARSER_SERVER_PORT": "\'12300\'"})`. Tests in https://github.com/sql-machine-learning/sqlflow/pull/3075 now pass. 

The root cause of this issue is that SQLFlow is [using an older version of Argo v2.4.3](https://github.com/sql-machine-learning/sqlflow/blob/c9d48b1bd61e7b369b1ace17219e0db6b1fb1b2b/go.sum#L33) where integer environment variables are not supported. Upgrading to newer versions of Argo would resolve the issue as well.

**Comment by merlintang** [comment] 2021-09-08 03:30
close this one.

**Closed by merlintang** 2021-09-08 03:30 UTC
Labels: bug
